'use strict';

/**
 * @file can_driver.js
 *
 * JavaScript analog of can_driver.c / can_driver.h generated by cantools
 * from PMSM-demo.dbc.
 *
 * All signals in this DBC use little-endian (Intel, @1) byte order.
 * Pack functions accept a plain object whose fields mirror the C struct.
 * Unpack functions return that same plain object.
 * Encode/decode helpers apply DBC scale & offset (physical ↔ raw).
 *
 * Usage (plain Node.js):
 *   const can = require('./can_driver');
 *   const buf = can.speedControlMsgPack({ control_cmd: can.CONTROL_CMD.CAN_CMD_START, speed_rpm: 1200 });
 *   const parsed = can.speedFeedbackMsgUnpack(rawBuffer);
 *   const physRpm = can.speedFeedbackMsgSpeedRpmDecode(parsed.speed_rpm);
 */

// ---------------------------------------------------------------------------
// Frame IDs (decimal values from DBC BO_ lines)
// ---------------------------------------------------------------------------
const FRAME_ID = Object.freeze({
    TORQUE_POWER_FEEDBACK_MSG:  0x240,   // 576
    PID_FEEDBACK_MSG:           0x230,   // 560
    VOLTAGE_TEMPER_FEEDBACK_MSG: 0x220,  // 544
    CURR_AMP_FEEDBACK_MSG:      0x210,   // 528
    SPEED_FEEDBACK_MSG:         0x200,   // 512
    SPEED_CONTROL_MSG:          0x100,   // 256
});

// Frame lengths in bytes
const FRAME_LENGTH = Object.freeze({
    TORQUE_POWER_FEEDBACK_MSG:   8,
    PID_FEEDBACK_MSG:            8,
    VOLTAGE_TEMPER_FEEDBACK_MSG: 4,
    CURR_AMP_FEEDBACK_MSG:       8,
    SPEED_FEEDBACK_MSG:          6,
    SPEED_CONTROL_MSG:           6,
});

// Motor_State enum (VAL_ 512 in DBC)
const MOTOR_STATE = Object.freeze({
    IDLE:             0,
    ALIGNMENT:        2,
    START:            4,
    RUN:              6,
    STOP:             8,
    FAULT_NOW:        10,
    FAULT_OVER:       11,
    WAIT_STOP_MOTOR:  20,
    OTF_DETECTION:    21,
    OTF_BRAKE:        22,
});

// Control_CMD enum (VAL_ 256 in DBC)
const CONTROL_CMD = Object.freeze({
    CAN_CMD_START:     1,
    CAN_CMD_STOP:      2,
    CAN_CMD_ACK_FAULT: 3,
});

// ---------------------------------------------------------------------------
// Torque_Power_feedback_MSG  (0x240, 8 bytes)
//   Torque : 0|32@1-  (int32,  scale=1, offset=0, range [-2, 2])
//   Power  : 32|32@1+ (uint32, scale=1, offset=0, range [0, 24])
// ---------------------------------------------------------------------------

/**
 * @param {{ torque: number, power: number }} msg  Raw (pre-encoded) values.
 * @returns {Buffer} 8-byte CAN payload.
 */
function torquePowerFeedbackMsgPack(msg) {
    const buf = Buffer.alloc(8);
    buf.writeInt32LE(msg.torque | 0, 0);
    buf.writeUInt32LE(msg.power >>> 0, 4);
    return buf;
}

/**
 * @param {Buffer} buf  8-byte CAN payload.
 * @returns {{ torque: number, power: number }}
 */
function torquePowerFeedbackMsgUnpack(buf) {
    if (buf.length < 8) throw new RangeError('Buffer too small for Torque_Power_feedback_MSG');
    return {
        torque: buf.readInt32LE(0),
        power:  buf.readUInt32LE(4),
    };
}

/** Physical Nm → raw int32 (scale=1) */
function torquePowerFeedbackMsgTorqueEncode(value) { return Math.trunc(value); }
/** Raw int32 → physical Nm */
function torquePowerFeedbackMsgTorqueDecode(raw)   { return raw; }
/** Range: [-2, 2] */
function torquePowerFeedbackMsgTorqueIsInRange(raw) { return raw >= -2 && raw <= 2; }

/** Physical W → raw uint32 (scale=1) */
function torquePowerFeedbackMsgPowerEncode(value) { return Math.trunc(value) >>> 0; }
/** Raw uint32 → physical W */
function torquePowerFeedbackMsgPowerDecode(raw)   { return raw; }
/** Range: [0, 24] */
function torquePowerFeedbackMsgPowerIsInRange(raw) { return raw >= 0 && raw <= 24; }

// ---------------------------------------------------------------------------
// PID_feedback_MSG  (0x230, 8 bytes)
//   PID_SPEED_KI  : 0|16@1+   PID_SPEED_KP  : 16|16@1+
//   PID_TORQUE_KI : 32|16@1+  PID_TORQUE_KP : 48|16@1+
//   All uint16, scale=1, offset=0, range [0, 65535]
// ---------------------------------------------------------------------------

/**
 * @param {{ pid_speed_ki: number, pid_speed_kp: number,
 *           pid_torque_ki: number, pid_torque_kp: number }} msg
 * @returns {Buffer}
 */
function pidFeedbackMsgPack(msg) {
    const buf = Buffer.alloc(8);
    buf.writeUInt16LE(msg.pid_speed_ki  & 0xFFFF, 0);
    buf.writeUInt16LE(msg.pid_speed_kp  & 0xFFFF, 2);
    buf.writeUInt16LE(msg.pid_torque_ki & 0xFFFF, 4);
    buf.writeUInt16LE(msg.pid_torque_kp & 0xFFFF, 6);
    return buf;
}

/** @returns {{ pid_speed_ki, pid_speed_kp, pid_torque_ki, pid_torque_kp }} */
function pidFeedbackMsgUnpack(buf) {
    if (buf.length < 8) throw new RangeError('Buffer too small for PID_feedback_MSG');
    return {
        pid_speed_ki:  buf.readUInt16LE(0),
        pid_speed_kp:  buf.readUInt16LE(2),
        pid_torque_ki: buf.readUInt16LE(4),
        pid_torque_kp: buf.readUInt16LE(6),
    };
}

function pidFeedbackMsgPidSpeedKiEncode(v)         { return Math.trunc(v) & 0xFFFF; }
function pidFeedbackMsgPidSpeedKiDecode(raw)        { return raw; }
function pidFeedbackMsgPidSpeedKiIsInRange(raw)     { return raw >= 0 && raw <= 65535; }

function pidFeedbackMsgPidSpeedKpEncode(v)          { return Math.trunc(v) & 0xFFFF; }
function pidFeedbackMsgPidSpeedKpDecode(raw)        { return raw; }
function pidFeedbackMsgPidSpeedKpIsInRange(raw)     { return raw >= 0 && raw <= 65535; }

function pidFeedbackMsgPidTorqueKiEncode(v)         { return Math.trunc(v) & 0xFFFF; }
function pidFeedbackMsgPidTorqueKiDecode(raw)       { return raw; }
function pidFeedbackMsgPidTorqueKiIsInRange(raw)    { return raw >= 0 && raw <= 65535; }

function pidFeedbackMsgPidTorqueKpEncode(v)         { return Math.trunc(v) & 0xFFFF; }
function pidFeedbackMsgPidTorqueKpDecode(raw)       { return raw; }
function pidFeedbackMsgPidTorqueKpIsInRange(raw)    { return raw >= 0 && raw <= 65535; }

// ---------------------------------------------------------------------------
// Voltage_Temper_feedback_MSG  (0x220, 4 bytes)
//   Bus_Voltage : 0|16@1+   (uint16, scale=1, offset=0, range [0, 45])
//   Temperature : 16|16@1+  (uint16, scale=1, offset=0, range [0, 200])
// ---------------------------------------------------------------------------

/**
 * @param {{ bus_voltage: number, temperature: number }} msg
 * @returns {Buffer}
 */
function voltageTemperFeedbackMsgPack(msg) {
    const buf = Buffer.alloc(4);
    buf.writeUInt16LE(msg.bus_voltage  & 0xFFFF, 0);
    buf.writeUInt16LE(msg.temperature  & 0xFFFF, 2);
    return buf;
}

/** @returns {{ bus_voltage, temperature }} */
function voltageTemperFeedbackMsgUnpack(buf) {
    if (buf.length < 4) throw new RangeError('Buffer too small for Voltage_Temper_feedback_MSG');
    return {
        bus_voltage: buf.readUInt16LE(0),
        temperature: buf.readUInt16LE(2),
    };
}

function voltageTemperFeedbackMsgBusVoltageEncode(v)        { return Math.trunc(v) & 0xFFFF; }
function voltageTemperFeedbackMsgBusVoltageDecode(raw)      { return raw; }
function voltageTemperFeedbackMsgBusVoltageIsInRange(raw)   { return raw >= 0 && raw <= 45; }

function voltageTemperFeedbackMsgTemperatureEncode(v)       { return Math.trunc(v) & 0xFFFF; }
function voltageTemperFeedbackMsgTemperatureDecode(raw)     { return raw; }
function voltageTemperFeedbackMsgTemperatureIsInRange(raw)  { return raw >= 0 && raw <= 200; }

// ---------------------------------------------------------------------------
// Curr_Amp_feedback_MSG  (0x210, 8 bytes)
//   I_D : 0|32@1-   (int32, scale=0.0001, offset=0, range [0, 5] A)
//   I_Q : 32|32@1-  (int32, scale=0.0001, offset=0, range [0, 5] A)
// ---------------------------------------------------------------------------

/**
 * @param {{ i_d: number, i_q: number }} msg  Raw (pre-encoded) values.
 * @returns {Buffer}
 */
function currAmpFeedbackMsgPack(msg) {
    const buf = Buffer.alloc(8);
    buf.writeInt32LE(msg.i_d | 0, 0);
    buf.writeInt32LE(msg.i_q | 0, 4);
    return buf;
}

/** @returns {{ i_d, i_q }}  Raw int32 values — divide by 0.0001 for Amps. */
function currAmpFeedbackMsgUnpack(buf) {
    if (buf.length < 8) throw new RangeError('Buffer too small for Curr_Amp_feedback_MSG');
    return {
        i_d: buf.readInt32LE(0),
        i_q: buf.readInt32LE(4),
    };
}

/** Physical A → raw int32  (1 A → 10000) */
function currAmpFeedbackMsgIDEncode(value)       { return Math.trunc(value / 0.0001); }
/** Raw int32 → physical A */
function currAmpFeedbackMsgIDDecode(raw)         { return raw * 0.0001; }
/** Range check on raw value: [0, 50000] */
function currAmpFeedbackMsgIDIsInRange(raw)      { return raw >= 0 && raw <= 50000; }

function currAmpFeedbackMsgIQEncode(value)       { return Math.trunc(value / 0.0001); }
function currAmpFeedbackMsgIQDecode(raw)         { return raw * 0.0001; }
function currAmpFeedbackMsgIQIsInRange(raw)      { return raw >= 0 && raw <= 50000; }

// ---------------------------------------------------------------------------
// Speed_feedback_MSG  (0x200, 6 bytes)
//   Motor_State : 0|8@1+   (uint8,  scale=1, offset=0 — see MOTOR_STATE enum)
//   Speed_RPM   : 8|32@1-  (int32,  scale=1, offset=0, range [-1750, 1750] RPM)
//   byte 5 is unused / zero
// ---------------------------------------------------------------------------

/**
 * @param {{ motor_state: number, speed_rpm: number }} msg
 * @returns {Buffer}
 */
function speedFeedbackMsgPack(msg) {
    const buf = Buffer.alloc(6);
    buf[0] = msg.motor_state & 0xFF;
    buf.writeInt32LE(msg.speed_rpm | 0, 1);   // bytes 1-4
    // byte 5 stays 0
    return buf;
}

/** @returns {{ motor_state, speed_rpm }} */
function speedFeedbackMsgUnpack(buf) {
    if (buf.length < 6) throw new RangeError('Buffer too small for Speed_feedback_MSG');
    return {
        motor_state: buf[0],
        speed_rpm:   buf.readInt32LE(1),
    };
}

function speedFeedbackMsgMotorStateEncode(v)        { return Math.trunc(v) & 0xFF; }
function speedFeedbackMsgMotorStateDecode(raw)      { return raw; }
function speedFeedbackMsgMotorStateIsInRange(raw)   { return raw >= 0 && raw <= 255; }

function speedFeedbackMsgSpeedRpmEncode(v)          { return Math.trunc(v) | 0; }
function speedFeedbackMsgSpeedRpmDecode(raw)        { return raw; }
function speedFeedbackMsgSpeedRpmIsInRange(raw)     { return raw >= -1750 && raw <= 1750; }

// ---------------------------------------------------------------------------
// Speed_control_MSG  (0x100, 6 bytes)
//   Control_CMD : 0|8@1+   (uint8, see CONTROL_CMD enum)
//   Speed_RPM   : 8|32@1-  (int32, scale=1, offset=0, range [-1750, 1750] RPM)
//   byte 5 is unused / zero
// ---------------------------------------------------------------------------

/**
 * @param {{ control_cmd: number, speed_rpm: number }} msg
 * @returns {Buffer}
 */
function speedControlMsgPack(msg) {
    const buf = Buffer.alloc(6);
    buf[0] = msg.control_cmd & 0xFF;
    buf.writeInt32LE(msg.speed_rpm | 0, 1);   // bytes 1-4
    return buf;
}

/** @returns {{ control_cmd, speed_rpm }} */
function speedControlMsgUnpack(buf) {
    if (buf.length < 6) throw new RangeError('Buffer too small for Speed_control_MSG');
    return {
        control_cmd: buf[0],
        speed_rpm:   buf.readInt32LE(1),
    };
}

function speedControlMsgControlCmdEncode(v)         { return Math.trunc(v) & 0xFF; }
function speedControlMsgControlCmdDecode(raw)       { return raw; }
function speedControlMsgControlCmdIsInRange(raw)    { return raw >= 0 && raw <= 255; }

function speedControlMsgSpeedRpmEncode(v)           { return Math.trunc(v) | 0; }
function speedControlMsgSpeedRpmDecode(raw)         { return raw; }
function speedControlMsgSpeedRpmIsInRange(raw)      { return raw >= -1750 && raw <= 1750; }

// ---------------------------------------------------------------------------
// Generic frame dispatcher
// ---------------------------------------------------------------------------

const _UNPACK_MAP = {
    [FRAME_ID.TORQUE_POWER_FEEDBACK_MSG]:   (b) => ({ _msg: 'Torque_Power_feedback_MSG',   ...torquePowerFeedbackMsgUnpack(b) }),
    [FRAME_ID.PID_FEEDBACK_MSG]:            (b) => ({ _msg: 'PID_feedback_MSG',            ...pidFeedbackMsgUnpack(b) }),
    [FRAME_ID.VOLTAGE_TEMPER_FEEDBACK_MSG]: (b) => ({ _msg: 'Voltage_Temper_feedback_MSG', ...voltageTemperFeedbackMsgUnpack(b) }),
    [FRAME_ID.CURR_AMP_FEEDBACK_MSG]:       (b) => ({ _msg: 'Curr_Amp_feedback_MSG',       ...currAmpFeedbackMsgUnpack(b) }),
    [FRAME_ID.SPEED_FEEDBACK_MSG]:          (b) => ({ _msg: 'Speed_feedback_MSG',          ...speedFeedbackMsgUnpack(b) }),
    [FRAME_ID.SPEED_CONTROL_MSG]:           (b) => ({ _msg: 'Speed_control_MSG',           ...speedControlMsgUnpack(b) }),
};

/**
 * Dispatch-unpack any known frame by its ID.
 * Returns null for unknown IDs.
 *
 * @param {number} frameId
 * @param {Buffer|Uint8Array|number[]} data
 * @returns {object|null}
 */
function unpackFrame(frameId, data) {
    const fn = _UNPACK_MAP[frameId];
    if (!fn) return null;
    return fn(Buffer.isBuffer(data) ? data : Buffer.from(data));
}

// ---------------------------------------------------------------------------
// Module exports
// ---------------------------------------------------------------------------
module.exports = {
    // Constants
    FRAME_ID,
    FRAME_LENGTH,
    MOTOR_STATE,
    CONTROL_CMD,

    // Torque_Power_feedback_MSG
    torquePowerFeedbackMsgPack,
    torquePowerFeedbackMsgUnpack,
    torquePowerFeedbackMsgTorqueEncode,
    torquePowerFeedbackMsgTorqueDecode,
    torquePowerFeedbackMsgTorqueIsInRange,
    torquePowerFeedbackMsgPowerEncode,
    torquePowerFeedbackMsgPowerDecode,
    torquePowerFeedbackMsgPowerIsInRange,

    // PID_feedback_MSG
    pidFeedbackMsgPack,
    pidFeedbackMsgUnpack,
    pidFeedbackMsgPidSpeedKiEncode,
    pidFeedbackMsgPidSpeedKiDecode,
    pidFeedbackMsgPidSpeedKiIsInRange,
    pidFeedbackMsgPidSpeedKpEncode,
    pidFeedbackMsgPidSpeedKpDecode,
    pidFeedbackMsgPidSpeedKpIsInRange,
    pidFeedbackMsgPidTorqueKiEncode,
    pidFeedbackMsgPidTorqueKiDecode,
    pidFeedbackMsgPidTorqueKiIsInRange,
    pidFeedbackMsgPidTorqueKpEncode,
    pidFeedbackMsgPidTorqueKpDecode,
    pidFeedbackMsgPidTorqueKpIsInRange,

    // Voltage_Temper_feedback_MSG
    voltageTemperFeedbackMsgPack,
    voltageTemperFeedbackMsgUnpack,
    voltageTemperFeedbackMsgBusVoltageEncode,
    voltageTemperFeedbackMsgBusVoltageDecode,
    voltageTemperFeedbackMsgBusVoltageIsInRange,
    voltageTemperFeedbackMsgTemperatureEncode,
    voltageTemperFeedbackMsgTemperatureDecode,
    voltageTemperFeedbackMsgTemperatureIsInRange,

    // Curr_Amp_feedback_MSG
    currAmpFeedbackMsgPack,
    currAmpFeedbackMsgUnpack,
    currAmpFeedbackMsgIDEncode,
    currAmpFeedbackMsgIDDecode,
    currAmpFeedbackMsgIDIsInRange,
    currAmpFeedbackMsgIQEncode,
    currAmpFeedbackMsgIQDecode,
    currAmpFeedbackMsgIQIsInRange,

    // Speed_feedback_MSG
    speedFeedbackMsgPack,
    speedFeedbackMsgUnpack,
    speedFeedbackMsgMotorStateEncode,
    speedFeedbackMsgMotorStateDecode,
    speedFeedbackMsgMotorStateIsInRange,
    speedFeedbackMsgSpeedRpmEncode,
    speedFeedbackMsgSpeedRpmDecode,
    speedFeedbackMsgSpeedRpmIsInRange,

    // Speed_control_MSG
    speedControlMsgPack,
    speedControlMsgUnpack,
    speedControlMsgControlCmdEncode,
    speedControlMsgControlCmdDecode,
    speedControlMsgControlCmdIsInRange,
    speedControlMsgSpeedRpmEncode,
    speedControlMsgSpeedRpmDecode,
    speedControlMsgSpeedRpmIsInRange,

    // Generic dispatcher
    unpackFrame,
};
